[build]
  publish = "public"
  command = "gatsby build"
[build.environment]
  NODE_VERSION = "12.15.0"
  YARN_VERSION = "1.22.4"
  YARN_FLAGS = "--no-ignore-optional"
[[plugins]]
  package = "netlify-plugin-gatsby-cache"
